// Declarative admin resource definitions. Each field maps to a (possibly nested) path in
// the API document. Field types are rendered by ResourceForm:
//   text, textarea, number, select, multi (chips), tags (comma list), bool, tri,
//   point (lat/lng), datetime, date, images, links, sources, hours, section (heading)
import {
  PLACE_CATEGORIES,
  EXTRA_CATEGORIES,
  MOODS,
  FOOD_CATEGORIES,
  STAY_TYPES,
  TRAVELLER_TYPES,
  STAY_EXPERIENCES,
  EVENT_CATEGORIES,
  PRICE_BANDS,
} from '../../utils/constants';
import { DISTRICT_SLUGS } from '../../utils/format';

const TRI = ['unknown', 'yes', 'no', 'partial'];
const BUSINESS_KINDS = ['restaurant', 'cafe', 'street-food', 'bakery', 'mall', 'market', 'street-shopping', 'handicrafts', 'souvenirs', 'spices', 'clothing', 'tea-coffee', 'local-specialties', 'theatre', 'park', 'childrens-park', 'theme-park', 'water-park', 'zoo', 'aquarium', 'indoor-entertainment', 'gaming-zone', 'hospital', 'pharmacy', 'police', 'atm', 'fuel', 'ev-charging', 'public-toilet'];
const TRANSPORT_KINDS = ['bus-stand', 'bus-stop', 'railway-station', 'metro-station', 'water-metro', 'airport', 'taxi-stand', 'auto-stand', 'bike-rental', 'car-rental', 'parking', 'boat-jetty'];
const ROUTE_STOP_KINDS = ['viewpoint', 'food-stop', 'tea-coffee', 'rest-area', 'fuel', 'ev-charging', 'public-toilet', 'hospital', 'attraction'];
const SAFETY_TYPES = ['swimming-restriction', 'strong-currents', 'slippery-terrain', 'wildlife-risk', 'restricted-area', 'road-condition', 'night-restriction', 'monsoon-closure', 'official-advisory', 'other'];

const district = { name: 'district', label: 'District', type: 'select', options: DISTRICT_SLUGS, required: true };
const location = { name: 'location', label: 'Location (WGS84)', type: 'point', required: true };
const workflowFields = [
  { type: 'section', label: 'Sources & flags' },
  { name: 'sources', label: 'Official sources', type: 'sources' },
  { name: 'isDemo', label: 'Demo / sample content', type: 'bool' },
];
const accessibility = [
  { type: 'section', label: 'Accessibility' },
  ...['wheelchair', 'elderlyFriendly', 'strollerFriendly', 'accessibleToilets', 'lift', 'stairsOrSlopes'].map((k) => ({ name: `accessibility.${k}`, label: k, type: 'tri' })),
  { name: 'accessibility.parkingDistanceM', label: 'Parking distance (m)', type: 'number' },
  { name: 'accessibility.walkingDistanceM', label: 'Walking distance (m)', type: 'number' },
  { name: 'accessibility.notes', label: 'Accessibility notes', type: 'textarea' },
  { name: 'accessibility.confirmed', label: 'Accessibility details confirmed', type: 'bool' },
];
const contact = [
  { name: 'contact.phone', label: 'Phone', type: 'text' },
  { name: 'contact.email', label: 'Email', type: 'text' },
  { name: 'contact.website', label: 'Website', type: 'text' },
  { name: 'contact.address', label: 'Address', type: 'text' },
];

export const RESOURCES = {
  places: {
    title: 'Places',
    singular: 'destination',
    workflow: true,
    featurable: true,
    publicPath: (d) => `/places/${d.slug}`,
    columns: ['name', 'district', 'categories', 'status', 'featured'],
    filters: { district: DISTRICT_SLUGS },
    fields: [
      { type: 'section', label: 'Basics' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'nameMl', label: 'Name (Malayalam)', type: 'text' },
      { name: 'alternateNames', label: 'Alternate names / spellings', type: 'tags' },
      { name: 'slug', label: 'URL slug (optional)', type: 'text' },
      district,
      { name: 'locality', label: 'Locality', type: 'text' },
      location,
      { name: 'categories', label: 'Categories', type: 'multi', options: [...PLACE_CATEGORIES, ...EXTRA_CATEGORIES] },
      { name: 'moods', label: 'Moods', type: 'multi', options: MOODS },
      { name: 'tags', label: 'Tags', type: 'tags' },
      { name: 'shortDescription', label: 'Short description', type: 'textarea', maxLength: 280 },
      { name: 'shortDescriptionMl', label: 'Short description (Malayalam)', type: 'textarea' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 6 },
      { name: 'descriptionMl', label: 'Description (Malayalam)', type: 'textarea', rows: 6 },
      { name: 'images', label: 'Images', type: 'images' },
      { type: 'section', label: 'Visiting' },
      { name: 'visitDurationHours', label: 'Typical visit (hours)', type: 'number' },
      { name: 'weekendGetaway', label: 'Weekend getaway', type: 'bool' },
      { name: 'budgetLevel', label: 'Budget level', type: 'select', options: ['unknown', 'free', 'budget', 'moderate', 'premium'] },
      { name: 'bestMonths', label: 'Best months (1–12)', type: 'tags', numeric: true },
      { name: 'indoor', label: 'Indoor / rainy-day friendly', type: 'bool' },
      { name: 'familyFriendly', label: 'Family friendly', type: 'tri' },
      { name: 'crowdLevel', label: 'Crowd level', type: 'select', options: ['unknown', 'low', 'moderate', 'high'] },
      { name: 'openingHours', label: 'Opening hours', type: 'hours' },
      { name: 'entryFee.isFree', label: 'Free entry', type: 'bool' },
      { name: 'entryFee.amount', label: 'Entry fee (₹)', type: 'number' },
      { name: 'entryFee.notes', label: 'Fee notes', type: 'text' },
      { name: 'entryFee.verified', label: 'Entry fee verified', type: 'bool' },
      ...contact,
      { name: 'officialLinks', label: 'Official links', type: 'links' },
      { name: 'facilities', label: 'Facilities', type: 'tags' },
      { type: 'section', label: 'Safety' },
      ...['swimmingRestricted', 'strongCurrents', 'slipperyTerrain', 'wildlifeRisk', 'restrictedAreas', 'nightAccessRestricted', 'monsoonClosure'].map((k) => ({ name: `safety.${k}`, label: k, type: 'tri' })),
      { name: 'safety.notes', label: 'Safety notes', type: 'textarea' },
      { name: 'safety.verified', label: 'Safety details verified', type: 'bool' },
      { name: 'safety.lastReviewedAt', label: 'Safety last reviewed', type: 'date' },
      ...accessibility,
      { type: 'section', label: 'Hidden gem' },
      { name: 'hiddenGem', label: 'Hidden gem', type: 'bool' },
      { name: 'gemDetails.accessDifficulty', label: 'Access difficulty', type: 'select', options: ['unknown', 'easy', 'moderate', 'difficult'] },
      { name: 'gemDetails.roadCondition', label: 'Road condition', type: 'select', options: ['unknown', 'good', 'fair', 'poor', 'offroad'] },
      { name: 'gemDetails.parking', label: 'Parking', type: 'tri' },
      { name: 'gemDetails.mobileNetwork', label: 'Mobile network', type: 'select', options: ['unknown', 'good', 'patchy', 'none'] },
      { name: 'gemDetails.monsoonSuitable', label: 'Monsoon suitable', type: 'tri' },
      { name: 'gemDetails.bestTimeToVisit', label: 'Best time to visit', type: 'text' },
      ...workflowFields,
    ],
  },
  businesses: {
    title: 'Food & businesses',
    singular: 'listing',
    workflow: true,
    featurable: true,
    publicPath: (d) => `/listings/${d.slug}`,
    columns: ['name', 'kind', 'district', 'status'],
    filters: { district: DISTRICT_SLUGS, kind: BUSINESS_KINDS },
    fields: [
      { type: 'section', label: 'Basics' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'nameMl', label: 'Name (Malayalam)', type: 'text' },
      { name: 'kind', label: 'Kind', type: 'select', options: BUSINESS_KINDS, required: true },
      district,
      { name: 'locality', label: 'Locality', type: 'text' },
      location,
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'descriptionMl', label: 'Description (Malayalam)', type: 'textarea' },
      { name: 'images', label: 'Images', type: 'images' },
      { name: 'priceRange', label: 'Price range', type: 'select', options: ['unknown', ...PRICE_BANDS] },
      { name: 'openingHours', label: 'Opening hours', type: 'hours' },
      { name: 'facilities', label: 'Facilities', type: 'tags' },
      ...contact,
      { name: 'officialWebsite', label: 'Official website', type: 'text' },
      { name: 'tags', label: 'Tags', type: 'tags' },
      { type: 'section', label: 'Food details' },
      { name: 'food.categories', label: 'Food categories', type: 'multi', options: FOOD_CATEGORIES },
      { name: 'food.cuisines', label: 'Cuisines', type: 'tags' },
      { name: 'food.dietary', label: 'Dietary', type: 'multi', options: ['vegetarian', 'vegan', 'non-vegetarian', 'seafood', 'contains-nuts', 'gluten-free', 'halal'] },
      { name: 'food.lateNight', label: 'Open late', type: 'bool' },
      { type: 'section', label: 'Theatre details' },
      { name: 'theatre.languages', label: 'Languages', type: 'tags' },
      { name: 'theatre.screens', label: 'Screens', type: 'number' },
      { name: 'theatre.showtimesUrl', label: 'Official showtimes URL', type: 'text' },
      { name: 'theatre.parking', label: 'Parking', type: 'text' },
      { name: 'shopping.productTypes', label: 'Products (shopping)', type: 'tags' },
      ...accessibility,
      ...workflowFields,
    ],
  },
  dishes: {
    title: 'Dishes',
    singular: 'dish',
    workflow: true,
    featurable: true,
    publicPath: (d) => `/food/dishes/${d.slug}`,
    columns: ['name', 'region', 'status'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'nameMl', label: 'Name (Malayalam)', type: 'text' },
      { name: 'alternateNames', label: 'Alternate names', type: 'tags' },
      { name: 'region', label: 'Region', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'descriptionMl', label: 'Description (Malayalam)', type: 'textarea' },
      { name: 'images', label: 'Images', type: 'images' },
      { name: 'categories', label: 'Categories', type: 'multi', options: FOOD_CATEGORIES },
      { name: 'dietary', label: 'Dietary', type: 'multi', options: ['vegetarian', 'vegan', 'non-vegetarian', 'seafood', 'contains-nuts', 'gluten-free', 'halal'] },
      { name: 'typicalPrice.band', label: 'Typical price band', type: 'select', options: ['unknown', ...PRICE_BANDS] },
      { name: 'typicalPrice.note', label: 'Price note', type: 'text' },
      { name: 'typicalPrice.estimated', label: 'Price is an estimate', type: 'bool' },
      ...workflowFields,
    ],
  },
  stays: {
    title: 'Stays',
    singular: 'stay',
    workflow: true,
    featurable: true,
    publicPath: (d) => `/stays/${d.slug}`,
    columns: ['name', 'type', 'district', 'priceBand', 'status'],
    filters: { district: DISTRICT_SLUGS, type: STAY_TYPES },
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'nameMl', label: 'Name (Malayalam)', type: 'text' },
      { name: 'type', label: 'Type', type: 'select', options: STAY_TYPES, required: true },
      district,
      { name: 'locality', label: 'Locality', type: 'text' },
      location,
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'images', label: 'Images', type: 'images' },
      { name: 'priceBand', label: 'Price band', type: 'select', options: ['unknown', ...PRICE_BANDS] },
      { name: 'priceFrom', label: 'Price from (₹/night)', type: 'number' },
      { name: 'priceVerified', label: 'Price verified', type: 'bool' },
      { name: 'facilities', label: 'Amenities', type: 'tags' },
      { name: 'travellerTypes', label: 'Traveller types', type: 'multi', options: TRAVELLER_TYPES },
      { name: 'experiences', label: 'Experiences', type: 'multi', options: STAY_EXPERIENCES },
      { name: 'bookingLinks', label: 'Booking links', type: 'links' },
      ...contact,
      ...accessibility,
      ...workflowFields,
    ],
  },
  events: {
    title: 'Events',
    singular: 'event',
    workflow: true,
    featurable: true,
    nameField: 'title',
    publicPath: (d) => `/events/${d.slug}`,
    columns: ['title', 'category', 'district', 'startDate', 'status'],
    filters: { district: DISTRICT_SLUGS, category: EVENT_CATEGORIES },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'titleMl', label: 'Title (Malayalam)', type: 'text' },
      { name: 'category', label: 'Category', type: 'select', options: EVENT_CATEGORIES, required: true },
      district,
      { name: 'organizer', label: 'Organizer', type: 'text' },
      { name: 'venue', label: 'Venue', type: 'text' },
      { name: 'location', label: 'Venue location', type: 'point' },
      { name: 'startDate', label: 'Starts', type: 'datetime', required: true },
      { name: 'endDate', label: 'Ends', type: 'datetime', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'descriptionMl', label: 'Description (Malayalam)', type: 'textarea' },
      { name: 'images', label: 'Images', type: 'images' },
      { name: 'entryFee.isFree', label: 'Free entry', type: 'bool' },
      { name: 'entryFee.amount', label: 'Entry fee (₹)', type: 'number' },
      { name: 'entryFee.notes', label: 'Fee notes', type: 'text' },
      { name: 'ticketStatus', label: 'Ticket status', type: 'select', options: ['unknown', 'free', 'available', 'limited', 'sold-out', 'at-venue'] },
      { name: 'ticketUrl', label: 'Ticket URL', type: 'text' },
      { name: 'ageRestriction', label: 'Age restriction', type: 'text' },
      { name: 'parking', label: 'Parking', type: 'text' },
      { name: 'publicTransport', label: 'Public transport', type: 'text' },
      { name: 'languages', label: 'Languages', type: 'tags' },
      { name: 'officialSourceUrl', label: 'Official source URL', type: 'text' },
      { name: 'lastVerifiedAt', label: 'Last verified', type: 'datetime' },
      ...workflowFields,
    ],
  },
  districts: {
    title: 'Districts',
    singular: 'district',
    noCreate: true,
    publicPath: (d) => `/districts/${d.slug}`,
    columns: ['name', 'headquarters', 'updatedAt'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'nameMl', label: 'Name (Malayalam)', type: 'text' },
      { name: 'headquarters', label: 'Headquarters', type: 'text' },
      { name: 'tagline', label: 'Tagline', type: 'text' },
      { name: 'taglineMl', label: 'Tagline (Malayalam)', type: 'text' },
      { name: 'intro', label: 'Introduction', type: 'textarea', rows: 5 },
      { name: 'introMl', label: 'Introduction (Malayalam)', type: 'textarea', rows: 5 },
      { name: 'location', label: 'Map centre', type: 'point' },
      { name: 'heroImage.url', label: 'Hero image URL', type: 'text' },
      { name: 'heroImage.alt', label: 'Hero image alt text', type: 'text' },
      { name: 'highlights', label: 'Highlights', type: 'tags' },
      { name: 'neighbours', label: 'Neighbouring districts', type: 'multi', options: DISTRICT_SLUGS },
      { name: 'transport.summary', label: 'Transport summary', type: 'textarea' },
      { name: 'essentials.summary', label: 'Essential services summary', type: 'textarea' },
      { name: 'sources', label: 'Sources', type: 'sources' },
      { name: 'isDemo', label: 'Text is unverified demo content', type: 'bool' },
    ],
  },
  transport: {
    title: 'Transport hubs',
    singular: 'transport node',
    workflow: true,
    columns: ['name', 'kind', 'district', 'status'],
    filters: { district: DISTRICT_SLUGS, kind: TRANSPORT_KINDS },
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'kind', label: 'Kind', type: 'select', options: TRANSPORT_KINDS, required: true },
      { name: 'code', label: 'Code', type: 'text' },
      district,
      location,
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'officialUrl', label: 'Official URL', type: 'text' },
      { name: 'scheduleUrl', label: 'Schedules URL', type: 'text' },
      ...workflowFields,
    ],
  },
  'route-stops': {
    title: 'Route stops',
    singular: 'route stop',
    workflow: true,
    columns: ['name', 'kind', 'district', 'status'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'kind', label: 'Kind', type: 'select', options: ROUTE_STOP_KINDS, required: true },
      district,
      location,
      { name: 'highway', label: 'Highway', type: 'text' },
      { name: 'toilets', label: 'Toilets', type: 'tri' },
      { name: 'parking', label: 'Parking', type: 'tri' },
      { name: 'description', label: 'Description', type: 'textarea' },
      ...workflowFields,
    ],
  },
  'safety-notices': {
    title: 'Safety notices',
    singular: 'notice',
    adminOnly: true,
    nameField: 'title',
    columns: ['title', 'severity', 'district', 'active', 'updatedAt'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'message', label: 'Message', type: 'textarea', required: true },
      { name: 'titleMl', label: 'Title (Malayalam)', type: 'text' },
      { name: 'messageMl', label: 'Message (Malayalam)', type: 'textarea' },
      { name: 'mlReviewed', label: 'Malayalam text human-reviewed', type: 'bool' },
      { name: 'type', label: 'Type', type: 'select', options: SAFETY_TYPES },
      { name: 'severity', label: 'Severity', type: 'select', options: ['info', 'caution', 'warning', 'danger'] },
      { name: 'district', label: 'District (optional)', type: 'select', options: ['', ...DISTRICT_SLUGS] },
      { name: 'targetType', label: 'Applies to type (optional)', type: 'select', options: ['', 'place', 'business', 'stay', 'event'] },
      { name: 'targetId', label: 'Applies to id (optional)', type: 'text' },
      { name: 'source', label: 'Source (required)', type: 'text', required: true },
      { name: 'sourceUrl', label: 'Source URL', type: 'text' },
      { name: 'validFrom', label: 'Valid from', type: 'datetime' },
      { name: 'validUntil', label: 'Valid until', type: 'datetime' },
      { name: 'active', label: 'Active', type: 'bool' },
      { name: 'isDemo', label: 'Demo content', type: 'bool' },
    ],
  },
  'emergency-contacts': {
    title: 'Emergency contacts',
    singular: 'contact',
    adminOnly: true,
    columns: ['name', 'number', 'category', 'verified', 'active'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'number', label: 'Number', type: 'text', required: true },
      { name: 'nameMl', label: 'Name (Malayalam)', type: 'text' },
      { name: 'mlReviewed', label: 'Malayalam name human-reviewed', type: 'bool' },
      { name: 'category', label: 'Category', type: 'select', options: ['general', 'police', 'ambulance', 'fire', 'women', 'child', 'tourist', 'disaster', 'other'] },
      { name: 'description', label: 'Description', type: 'text' },
      { name: 'scope', label: 'Scope', type: 'select', options: ['national', 'state', 'district'] },
      { name: 'district', label: 'District (district scope)', type: 'select', options: ['', ...DISTRICT_SLUGS] },
      { name: 'source', label: 'Source', type: 'text' },
      { name: 'sourceUrl', label: 'Source URL', type: 'text' },
      { name: 'verified', label: 'Verified against the official source', type: 'bool', help: 'Only tick after confirming the number with the cited official source.' },
      { name: 'order', label: 'Display order', type: 'number' },
      { name: 'active', label: 'Active', type: 'bool' },
    ],
  },
  translations: {
    title: 'Languages',
    singular: 'translation override',
    adminOnly: true,
    nameField: 'key',
    columns: ['lang', 'key', 'value', 'reviewed'],
    filters: { lang: ['en', 'ml', 'hi', 'ta', 'kn', 'ar', 'fr', 'de', 'ru'] },
    fields: [
      { name: 'lang', label: 'Language', type: 'select', options: ['en', 'ml', 'hi', 'ta', 'kn', 'ar', 'fr', 'de', 'ru'], required: true },
      { name: 'key', label: 'Key (e.g. home.heroTitle)', type: 'text', required: true },
      { name: 'value', label: 'Value', type: 'textarea', required: true },
      { name: 'reviewed', label: 'Human-reviewed', type: 'bool' },
    ],
  },
  knowledge: {
    title: 'AI knowledge',
    singular: 'knowledge note',
    adminOnly: true,
    nameField: 'title',
    columns: ['title', 'district', 'confidence', 'approved'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'body', label: 'Content', type: 'textarea', rows: 6, required: true },
      { name: 'district', label: 'District', type: 'select', options: ['', ...DISTRICT_SLUGS] },
      { name: 'topics', label: 'Topics', type: 'tags' },
      { name: 'confidence', label: 'Confidence', type: 'select', options: ['estimated', 'verified'] },
      { name: 'source', label: 'Source', type: 'text' },
      { name: 'sourceUrl', label: 'Source URL', type: 'text' },
      { name: 'approved', label: 'Approved for AI retrieval', type: 'bool' },
    ],
  },
};
