import { features } from '../../config/env.js';
import { gatherCandidates, scoreCandidates, planDemo, buildItinerary, dayCount } from './itineraryBuilder.js';
import { placeFacts } from './retrievalService.js';
import { planTripWithClaude } from './anthropicProvider.js';

const PER_DAY = { relaxed: 3, balanced: 4, packed: 6 };

/**
 * Generate an itinerary. With AI configured, Claude selects/orders candidate records;
 * otherwise (or on any AI failure) the deterministic demo planner is used. Either way
 * the result is built only from database records.
 */
export async function generateTrip(inputs) {
  const month = (inputs.startDate ? new Date(inputs.startDate) : new Date()).getMonth() + 1;
  const { start, candidates } = await gatherCandidates(inputs);
  const scored = scoreCandidates(candidates, inputs, month);

  if (!scored.length) {
    return {
      title: `Trip from ${start.label}`,
      inputs,
      days: [],
      summary: { warnings: ['No published places match these filters near the starting point. Try a longer duration or different interests.'] },
      generator: 'demo',
      empty: true,
    };
  }

  let plan;
  let generator = 'demo';
  let title;
  let notice = features.ai ? undefined : 'Demo planner: AI is not configured, so this itinerary was generated by rules from real database records.';

  if (features.ai) {
    try {
      const days = dayCount(inputs);
      const perDay = inputs.duration === 'few-hours' ? 2 : PER_DAY[inputs.pace] || 4;
      const shortlist = scored.slice(0, 40);
      const aiPlan = await planTripWithClaude({ inputs, candidates: shortlist.map(placeFacts), days, perDay });
      const byId = new Map(shortlist.map((p) => [String(p._id), p]));
      const seen = new Set();
      plan = aiPlan.days.slice(0, days).map((d) => ({
        // Drop any id that is not a real candidate — the AI cannot introduce places.
        places: d.placeIds.filter((id) => byId.has(id) && !seen.has(id) && seen.add(id)).slice(0, perDay).map((id) => byId.get(id)),
      }));
      if (!plan.some((d) => d.places.length)) throw new Error('AI plan contained no valid places');
      generator = 'ai';
      title = aiPlan.title;
    } catch (err) {
      notice = `AI planner unavailable (${err.message}); used the demo planner instead.`;
      plan = undefined;
    }
  }

  if (!plan) plan = planDemo(scored, inputs, start.coordinates);
  const trip = await buildItinerary({ inputs, plan, start, candidates, generator, title });
  if (notice) trip.notice = notice;
  return trip;
}
